export const SIGN_UP = "SIGN_UP"
export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const POST_FILTER = "POST_FILTER"
export const GET_FILTERS = "GET_FILTERS"
export const DELETE_FILTER = "DELETE_FILTER"